name: fe
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

  # BLOC and HTTP
  flutter_bloc: ^6.1.0
  formz: ^0.3.1
  equatable: ^1.2.5
  http: ^0.12.0+4
  flutter_form_bloc: ^0.19.0

  authentication_repository:
    path: packages/authentication_repository
  
  flutter_svg: ^0.18.0
  
  # env
  flutter_dotenv: ^3.1.0

  # Phone call
  url_launcher: ^5.7.10

  # Map Nagivation
  map_launcher: ^1.1.3
  geocoding: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.1

  # Launcher Icons
  flutter_launcher_icons: ^0.8.0
  
flutter_icons:
  android: true
  ios: true
  image_path: assets/icon_v1.1.0.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env